### ISSUE TITLE
Exception when reporting compiler error

### ISSUE THREAD

**Issue by bmerry** [Kattis/problemtools#160]
Using 1.20191126.devrev1-4 on Python 3.6:

```
Traceback (most recent call last):
  File "/home/bruce/compolymp/acm/2020world/ve/bin/verifyproblem", line 8, in <module>
    sys.exit(main())
  File "/home/bruce/compolymp/acm/2020world/ve/lib/python3.6/site-packages/problemtools/verifyproblem.py", line 1518, in main
    [errors, warnings] = prob.check(args)
  File "/home/bruce/compolymp/acm/2020world/ve/lib/python3.6/site-packages/problemtools/verifyproblem.py", line 1449, in check
    item.check(args)
  File "/home/bruce/compolymp/acm/2020world/ve/lib/python3.6/site-packages/problemtools/verifyproblem.py", line 1361, in check
    self.error('Compile error for %s submission %s' % (acr, sub), msg)
  File "/home/bruce/compolymp/acm/2020world/ve/lib/python3.6/site-packages/problemtools/verifyproblem.py", line 106, in error
    self, ProblemAspect.__append_additional_info(msg, additional_info))
  File "/home/bruce/compolymp/acm/2020world/ve/lib/python3.6/site-packages/problemtools/verifyproblem.py", line 95, in __append_additional_info
    lines = additional_info.split('\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by austrin** [comment]
Fixed in e0a88d0, thanks!
