### ISSUE TITLE
Required plasTeX version?

### ISSUE THREAD

**Issue by evouga** [Kattis/problemtools#214]
Does ProblemTools need an older version of plastTeX as a dependency? I get the following error when I try to run `problem2html`:

```
Traceback (most recent call last):
  File "/u/evouga/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/evouga/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/evouga/icpc/problemtools/problemtools/problem2html.py", line 140, in <module>
    main()
  File "/u/evouga/icpc/problemtools/problemtools/problem2html.py", line 136, in main
    convert(options.problem, options)
  File "/u/evouga/icpc/problemtools/problemtools/problem2html.py", line 41, in convert
    tex = plasTeX.TeX.TeX(myfile=texfile)
TypeError: __init__() got an unexpected keyword argument 'myfile'
```

**Comment by pyeatt** [comment]
I had the same issue.  Seems to be resolved.
