### ISSUE TITLE
error running verify problem in docker image

### ISSUE THREAD

**Issue by jifland** [Kattis/problemtools#279]
using the current source code and building the dozer image so it will run on my M1 Mac.
Clone the problem set repo onto the docker image.
run verify problem and am getting errors from the run of that program:
~~~
root@5552ef279509:/2024/na-central-rocky/problems# verifyproblem -h
Traceback (most recent call last):
  File "/usr/local/bin/verifyproblem", line 5, in <module>
    from problemtools.verifyproblem import main
  File "/usr/local/lib/python3.8/dist-packages/problemtools/verifyproblem.py", line 34, in <module>
    from . import run
  File "/usr/local/lib/python3.8/dist-packages/problemtools/run/__init__.py", line 7, in <module>
    from .buildrun import BuildRun
  File "/usr/local/lib/python3.8/dist-packages/problemtools/run/buildrun.py", line 12, in <module>
    from .program import Program
  File "/usr/local/lib/python3.8/dist-packages/problemtools/run/program.py", line 15, in <module>
    class Program(object):
  File "/usr/local/lib/python3.8/dist-packages/problemtools/run/program.py", line 58, in Program
    def compile(self) -> tuple[bool, str|None]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
~~~

**Comment by Tagl** [comment]
The issue here is the python version is 3.8 but 3.10 is required for the type hints.
So the solution would be to update the python version in the image, potentially using a virtual environment.

**Comment by jifland** [comment]
Thanks!  Got that updated and past this issue.
