### ISSUE TITLE
Crash involving problem_author when reinstalling a problem from scratch

### ISSUE THREAD

**Issue by ghamerly** [Kattis/problemtools#49]
I added a problem in my VM using:
`.../addproblem.sh -s 1 -a '2016-09-24 16:00' problems/anewalphabet`

Then I reinstalled it from scratch (ran the command above again and selected option "2", reinstall from scratch. The result was this:

```
hamerly@ubuntu:~/icpc/qualifier_2016$ /usr/local/kattis/bin/admin/addproblem.sh -s 1 -a '2016-09-24 16:00' problems/anewalphabet
Problem "anewalphabet" already in database.
There is already a directory in /usr/local/kattis/data/src/ for the backup of the problem package
It seems like the problem was already (partially) installed.
What to do?
 1) Update problem (keep submissions).
   This will remove and reinstall all files (statement, data, validator) and update db entry.
 2) Reinstall from scratch.
   In addition to the above this will remove the db entry and therefore all old submissions.
 3) Abort? (Default)
 [1-3]>2
Are you REALLY sure you want to remove the problem completely before reinstalling?  This will remove all existing submissions to the problem! [y/N]y
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kattis/admin/addproblem.py", line 826, in <module>
    main(args)
  File "/usr/lib/python2.7/dist-packages/kattis/admin/addproblem.py", line 734, in main
    is_update = determine_update_mode(conn, problemname, args)
  File "/usr/lib/python2.7/dist-packages/kattis/admin/addproblem.py", line 269, in determine_update_mode
    curs.execute('DELETE FROM problem WHERE problem_id=%(problem_id)d;', locals())
  File "/usr/lib/python2.7/dist-packages/pgdb.py", line 259, in execute
    self.executemany(operation, (params,))
  File "/usr/lib/python2.7/dist-packages/pgdb.py", line 289, in executemany
    raise DatabaseError("error '%s' in '%s'" % (msg, sql))
DatabaseError: error 'ERROR:  update or delete on table "problem" violates foreign key constraint "problem_problem_author_problem_id_fkey" on table "problem_problem_author"
DETAIL:  Key (problem_id)=(6) is still referenced from table "problem_problem_author".
' in 'DELETE FROM problem WHERE problem_id=6;'

Uncaught exception in addproblem (see above for details).  THIS IS A BUG.
```

**Comment by austrin** [comment]
Quick response: I can't remember the last time I tried doing that option in addproblem, so I'm not surprised that it is broken.

I actually had exactly the same issue for a different reason earlier today.  I think the correct fix is to simply update the Schema, changing the `problem_id` reference in the `problem_problem_author` table to `ON DELETE CASCADE`.

**Comment by austrin** [comment]
(As a workaround, manually deleting the corresponding entries from problem_problem_author should work.)

**Comment by ghamerly** [comment]
...and I just realized that in my sleep-deprived state this is the wrong repository to put this issue in. I'll move it over.
