### ISSUE TITLE
Crash in verifyproblem in v1.20170420

### ISSUE THREAD

**Issue by ghamerly** [Kattis/problemtools#65]
I was running v1.20170420 of problemtools and it crashes with the following (on a fairly generic ACM-style problem). The problem is in development and it has no secret test data (yet). Perhaps that is triggering the bug? I can get more information if that's helpful.

```
Loading problem progressivescramble
Checking config
Checking statement
/drone/src/github.com/na-icpc/naq17/problemset.cls exists, will not copy it -- in case of weirdness this is likely culprit
/drone/src/github.com/na-icpc/naq17/problemset.cls exists, will not copy it -- in case of weirdness this is likely culprit
Checking validators
Checking graders
Checking data
Checking submissions
Traceback (most recent call last):
 File "/usr/local/bin/verifyproblem", line 9, in <module>
   load_entry_point('problemtools===v1.20170420-1-g30ed959', 'console_scripts', 'verifyproblem')()
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 1220, in main
   [errors, warnings] = prob.check(args)
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 1174, in check
   item.check(args)
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 1091, in check
   res = self.check_submission(sub, args, acr, timelim, timelim_margin)
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 1050, in check_submission
   (result1, result2) = self._problem.testdata.run_submission(sub, args, timelim_low, timelim_high)
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 383, in run_submission
   (r1, r2) = subdata.run_submission(sub, args, timelim_low, timelim_high)
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 388, in run_submission
   return (self.aggregate_results(subres1),
 File "/usr/local/lib/python2.7/dist-packages/problemtools/verifyproblem.py", line 411, in aggregate_results
   res.testcase = sub_results[-1].testcase
IndexError: list index out of range
```

I expect this was introduced in https://github.com/Kattis/problemtools/pull/63/files

**Comment by austrin** [comment]
Fixed in develop.
