### ISSUE TITLE
verifyproblem crashes when there are no test cases in the data/secret

### ISSUE THREAD

**Issue by godmar** [Kattis/problemtools#66]
See subject.  Error trace is:

```
Traceback (most recent call last):st case sample/sample01...
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 1226, in <module>
    main()
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 1220, in main
    [errors, warnings] = prob.check(args)
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 1174, in check
    item.check(args)
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 1091, in check
    res = self.check_submission(sub, args, acr, timelim, timelim_margin)
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 1050, in check_submission
    (result1, result2) = self._problem.testdata.run_submission(sub, args, timelim_low, timelim_high)
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 383, in run_submission
    (r1, r2) = subdata.run_submission(sub, args, timelim_low, timelim_high)
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 388, in run_submission
    return (self.aggregate_results(subres1),
  File "/home/icpc.cs.vt.edu/icpc.cs.vt.edu/problemtools-1.20170420/problemtools/verifyproblem.py", line 411, in aggregate_results
    res.testcase = sub_results[-1].testcase
IndexError: list index out of range
```

**Comment by godmar** [comment]
sorry, duplicate of issue #65

**Comment by ghamerly** [comment]
@godmar for now use v1.20170408, which is stable.

You can install it via pip with:
```
pip install git+https://github.com/kattis/problemtools.git@v1.20170408
```
